plugins {
    id 'com.android.application'
}

android {
    namespace 'jp.xenia.emulator'
    compileSdk 34

    ndkVersion '28.2.13676358'

    defaultConfig {
        applicationId 'jp.xenia.emulator'
        // 24 (7.0) - Vulkan.
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName 'Prototype'

        ndk {
            abiFilters 'arm64-v8a', 'x86_64'
        }

        externalNativeBuild {
            cmake {
                arguments "-DANDROID_STL=c++_static"
                arguments "-DXENIA_HOST_TOOLS_DIR=${project.rootDir}/../../build-host/host_tools"
            }
        }
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['src/main/jniLibs']
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }

        debug {
            applicationIdSuffix '.debug'
            debuggable true
        }

        checked {
            applicationIdSuffix '.checked'
            debuggable true
        }
    }

    flavorDimensions 'distribution'

    productFlavors {
        github {
            dimension 'distribution'
            applicationIdSuffix '.github'
        }

        googlePlay {
            dimension 'distribution'
            // TODO(Triang3l): Provide a signing config for core contributors only.
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    externalNativeBuild {
        cmake {
            path file('../../../CMakeLists.txt')
            version "3.22.1"
        }
    }
}

configurations.all {
    resolutionStrategy {
        force 'org.jetbrains.kotlin:kotlin-stdlib:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22'
    }
}

dependencies {
    implementation 'org.jetbrains:annotations:15.0'

    implementation 'androidx.core:core:1.10.1'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.activity:activity:1.7.2'
}
