name: Build (reusable)

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Setup
        run: |
          pipx install clang-format==21.1.8
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - name: Lint
        run: ./xenia-build.py lint --all

  build-android:
    name: Build Android
    needs: lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup_ndk
        with:
          ndk-version: r28c
          add-to-path: true

      - name: Cache Slang
        id: cache-slang
        uses: actions/cache@v5
        with:
          path: .slang
          key: ${{ runner.os }}-${{ runner.arch }}-slang-2026.8

      - name: Download Slang
        if: steps.cache-slang.outputs.cache-hit != 'true'
        run: ./xenia-build.py slang

      - name: Setup
        run: |
          git submodule update --init --depth=1 -j$(getconf _NPROCESSORS_ONLN) $(grep -oP '(?<=path = )(?!third_party\/DirectXShaderCompiler).+' .gitmodules)
          ./xenia-build.py fetchdata

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.10

      - name: Build Host Tools
        env:
          SCCACHE_GHA_ENABLED: "true"
          CMAKE_C_COMPILER_LAUNCHER: sccache
          CMAKE_CXX_COMPILER_LAUNCHER: sccache
        run: |
         cmake -S . -B build-host \
          -G "Ninja" \
          -DXENIA_BUILD_MISC=ON \
          -DXENIA_ENABLE_LTO=OFF

         cmake --build build-host \
           --target xenia-shader-cc \
           --config Release \
           -j$(getconf _NPROCESSORS_ONLN)
      
      - name: Build Android NDK libraries
        env:
          SCCACHE_GHA_ENABLED: "true"
          CMAKE_C_COMPILER_LAUNCHER: sccache
          CMAKE_CXX_COMPILER_LAUNCHER: sccache
          ANDROID_NDK_ROOT: ${{ steps.setup_ndk.outputs.ndk-path }}
        run: |
          mkdir -p build-android/host_tools
          cp build-host/host_tools/xenia-shader-cc build-android/host_tools/
          cmake -S . -B build-android \
            -DCMAKE_SYSTEM_NAME=Android \
            -DCMAKE_SYSTEM_VERSION=24 \
            -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
            -DCMAKE_ANDROID_NDK=${{ steps.setup_ndk.outputs.ndk-path }} \
            -DCMAKE_ANDROID_PLATFORM=android-24 \
            -G "Ninja" \
            -DXENIA_ENABLE_LTO=OFF
          cmake --build build-android --config Release -j$(getconf _NPROCESSORS_ONLN)

      - name: Build Android APK
        working-directory: android/android_studio_project
        run: |
          ./gradlew assembleRelease

      - name: sccache stats
        if: always()
        run: sccache --show-stats

      - name: inspect shader compiler
        run: |
         file build-android/host_tools/xenia-shader-cc

      - name: Prepare artifacts
        id: prepare_artifacts
        run: |
          mkdir -p artifacts/android
          find . -name "*.apk" -exec cp {} artifacts/android/ \;
          cp LICENSE artifacts/android/

      - name: Upload xenia edge Android artifacts
        if: steps.prepare_artifacts.outcome == 'success'
        uses: actions/upload-artifact@v7
        with:
          name: xenia_edge_android
          path: artifacts/android
          if-no-files-found: error
