name: Nuke Cache

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  nuke-cache:
    name: purge caches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Delete Caches Loop
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Starting deletion of ALL caches..."
          
          while : ; do
            cache_ids=$(gh cache list --limit 100 --json id --jq '.[].id')
            
            if [ -z "$cache_ids" ]; then
              echo "No more caches found. Clean complete!"
              break
            fi

            for id in $cache_ids; do
              echo "Deleting cache ID: $id"
              gh cache delete "$id"
              
              sleep 0.2
            done
          done
