name: Sync Fork

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/has207/xenia-edge.git
          git fetch upstream edge

      - name: Merge upstream into edge
        run: |
          git checkout edge
          git merge upstream/edge -X ours --no-edit

      - name: Push updated branch
        run: |
          git push origin edge
